# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

jobs:
- job: Build
  pool:
    vmImage: 'windows-latest'
  steps:
  - task: Go@0
    inputs:
      command: 'build'
      arguments: '-o $(Build.ArtifactStagingDirectory)/terraform-provider-gandi.exe'
  - task: PublishBuildArtifacts@1
    inputs:
      ArtifactName: Build
- job: Archive
  dependsOn: Build
  pool:
    vmImage: 'ubuntu-18.04'
  steps:
  - task: DownloadSecureFile@1
    name: gcloud_keyfile
    inputs:
      secureFile: 'azure-pipelines-binaries.json'
  - task: DownloadBuildArtifacts@0
    inputs:
      artifactName: Build
      downloadPath: $(Pipeline.Workspace)
  - script: |
      docker run --rm -v $(gcloud_keyfile.secureFilePath):/secrets/gcloud-keyfile.json -v $(Pipeline.Workspace)/Build/terraform-provider-gandi.exe:/workspace/terraform-provider-gandi.exe google/cloud-sdk /bin/bash -c "gcloud auth activate-service-account --key-file /secrets/gcloud-keyfile.json && gsutil cp /workspace/terraform-provider-gandi.exe gs://pv-binaries/terraform-provider-gandi/$(version)/win32/terraform-provider-gandi.exe"
    displayName: Run gsutil



